version: "3"

networks:
  app-tier:
    driver: bridge
services:
  app:
    build: ./
    image: cours-sql:latest
    links:
      - db
    networks:
      - app-tier
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
  db:
    image: mariadb
    container_name: classicmodels2_db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=classicmodels
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-tier
